### ISSUE TITLE
[FEAT] Create home page

### ISSUE THREAD

**Issue by Noxaelum** [MAKIENAUT/KM2C#19]
I'll be creating the home page na. That means I'll be adding their logo, the hero image in the figma design and the draft selection of cv, filmography, and photography

**Comment by Noxaelum** [comment]
@MAKIENAUT Kindly check PR

**Comment by MAKIENAUT** [comment]
@Noxaelum please always do the diligence of moving your issues to the "To Validate" status for the other devs to be able to pick it up when they're free.

**Comment by MAKIENAUT** [comment]
Checking this issue now...
